version:  "2.36.0"

services:
  pg:
    image: postgres:alpine
    container_name: alijahon
    restart: always
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql
  alijahon:
    build: .
    image: alijahon:alpine
    container_name: alijahon_container
    depends_on:
      - pg
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8001"
    ports:
      - '8001:8001'
volumes:
  pg_data:
